export const TEST_DISPATCH = 'TEST_DISPATCH';
export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_DIAGRAMS = 'GET_DIAGRAMS';
export const GET_DIAGRAM = 'GET_DIAGRAM';
export const ADD_DIAGRAM = 'ADD_DIAGRAM';
export const NEW_DIAGRAM = 'NEW_DIAGRAM';
export const DIAGRAM_LOADING = 'DIAGRAM_LOADING';